services:
  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '127.0.0.1'
      dockerfile: Dockerfile
    image: ksul-openwebui
    container_name: open-webui
    volumes:
      - ./backend/data:/app/backend/data
      - ./backend:/app/backend
      - ./src:/app/src
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    env_file:
      - .env.example
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

